@LogiTrack_HostAddress = http://localhost:5087

GET {{LogiTrack_HostAddress}}/api/order
Accept: application/json
###

GET {{LogiTrack_HostAddress}}/api/order/13
Accept: application/json
###

POST {{LogiTrack_HostAddress}}/api/order
Accept: application/json
Content-Type: application/json

{
  "customerName": "Ena",
  "datePlaced": "2023-10-01T12:00:00Z",
  "items": [
    {
      "name": "MUFC Membership",
      "quantity": 1,
      "location": "Bruchsal"
    }
  ]
}
###

DELETE {{LogiTrack_HostAddress}}/api/order/120
Accept: application/json
###

GET {{LogiTrack_HostAddress}}/api/inventory
Accept: application/json
###

POST {{LogiTrack_HostAddress}}/api/inventory
Accept: application/json
Content-Type: application/json

{
  "name": "Smartphone",
  "quantity": 10,
  "location": "Bandung",
  "orderId": 130
}
###

DELETE {{LogiTrack_HostAddress}}/api/inventory/600
Accept: application/json
###