@LogiTrack_HostAddress = http://localhost:5087
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YjY4ZjZkYi00YWNhLTQzNTYtYmVkMC1hMTNmYzZmMDE4N2YiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJqdGkiOiJkMmYyMGQwNi02YjBhLTRjMTMtOTA2Zi0yMWM2MWY3MzFkODMiLCJuYW1lIjoiRXJ3aW4iLCJleHAiOjE3NDk4MTk0NDksImlzcyI6IkVMLUlzc3VlciIsImF1ZCI6IkVMLUF1ZGllbmNlIn0.wS7JAN_tKXa1-xdlr6dx3on1mUVB0RrdNb3Cu-lBmkU
}
GET {{LogiTrack_HostAddress}}
###

GET {{LogiTrack_HostAddress}}/api/Order
Accept: application/json
Authorization: Bearer {{Token}}
###

GET {{LogiTrack_HostAddress}}/api/Order/1
Accept: application/json
Authorization: Bearer {{Token}}
###

POST {{LogiTrack_HostAddress}}/api/Order
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "customerName": "Ena",
  "datePlaced": "2023-10-01T12:00:00Z",
  "items": [
    {
      "name": "MUFC Membership",
      "quantity": 1,
      "location": "Bruchsal"
    }
  ]
}
###

DELETE {{LogiTrack_HostAddress}}/api/Order/120
Accept: application/json
Authorization: Bearer {{Token}}
###

GET {{LogiTrack_HostAddress}}/api/Inventory
Accept: application/json
Authorization: Bearer {{Token}}
###

POST {{LogiTrack_HostAddress}}/api/Inventory
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "name": "Smartphone",
  "quantity": 10,
  "location": "Bandung",
  "orderId": 5
}
###

DELETE {{LogiTrack_HostAddress}}/api/Inventory/600
Accept: application/json
Authorization: Bearer {{Token}}
###

POST {{LogiTrack_HostAddress}}/api/auth/register
Accept: application/json
Content-Type: application/json

{
  "Email": "test@example.com",
  "Password": "Password123!",
  "Name": "Erwin"
}
###

POST {{LogiTrack_HostAddress}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "Email": "test@example.com",
  "Password": "Password123!"
}
###